index:
    path: /
    controller: App\Controller\HomepageController::index

ajax_get_game_info:
    path: /get_game_info_modal
    controller: App\Controller\ApiController::getGameInfo
    options:
        expose: true

ajax_get_games:
    path: /games
    controller: App\Controller\ApiController::getGames
    options:
        expose: true

ajax_get_paginated_games:
    path: /get_paginated_games
    controller: App\Controller\ApiController::getGamesPaginated
    options:
        expose: true

ajax_get_paginated_favourite_games:
    path: /get_paginated_favourite_games
    controller: App\Controller\ApiController::getFavouriteGamesPaginated
    options:
        expose: true

ajax_get_popular_moves:
    path: /get_popular_moves
    controller: App\Controller\ApiController::getPopularMoves
    options:
        expose: true

ajax_update_game:
    path: /ajax_update_game
    controller: App\Controller\ApiController::updateGame
    options:
        expose: true
