index:
    path: /
    controller: App\Controller\HomepageController::index

ajax_get_game_info:
    path: /game
    controller: App\Controller\ApiController::getGameInfo
    options:
        expose: true

ajax_get_games:
    path: /games
    controller: App\Controller\ApiController::getGames
    options:
        expose: true

ajax_get_paginated_games:
    path: /get_paginated_games
    controller: App\Controller\ApiController::getGamesPaginated
    options:
        expose: true